### ISSUE TITLE
Error when using rec.file

### ISSUE THREAD

**Issue by jkreinz** [jhavsmith/startmrca#10]
Hi Joel,

I've gotten your method to work when I specify a constant rec.rate, but when I use a rec.file, I get the following error:
> The recombination map has no non-zero values - transition probabilities can't be calculated.

I've made sure my map fie is formatted as yours, for e.g.

11 24000009 2.98969368814524e-05
11 24000014 2.79102432903216e-05
11 24000036 2.05374097384081e-05
11 24000055 1.68640498524038e-05
11 24000115 8.60108617506877e-06
11 24000118 7.76122673203818e-06
11 24000137 1.76792053804482e-06
11 24000144 1.45445478038888e-07
11 24000211 7.16872547697983e-07

Any advice would be greatly appreciated! Thanks,

**Comment by jhavsmith** [comment]
Hi Julia,

Huh, that error message doesn't make sense either. Thanks for letting me
know, I'll have a look.

Joel

**Comment by jhavsmith** [comment]
I just posted a new release. Let me know if you still find any issues. 

Joel
