### ISSUE TITLE
How to calculate the TMRCA and confidence interval according to the t.chain file?

### ISSUE THREAD

**Issue by Cecilia44** [jhavsmith/startmrca#11]
Hi, Joel,

I also have some questions about the result of t.chain. I run 10 independent MCMC chains with 10000 iterations. I have plotted the MCMC in the first column over iterations and found they are converged in each MCMC chains. Then how can I determine the exact TMRCA (mean value or median value of those converged values)? And how to calculate the confidence interval?

Thanks a lot!

**Comment by jhavsmith** [comment]
Hi! Glad to hear that your MCMCs are converging. Before you compute a point estimate and confidence interval, you should choose a "burnin", or number of iterations at the beginning of the MCMC to remove. If you look at the trace plots for the MCMCs you ran, there should be some number of iterations at the beginning that haven't converged. Here's an example trace plot after  running the example script from help(run.startmrca) with 5000 iterations:

![trace_example](https://user-images.githubusercontent.com/8657185/69501180-45bc6500-0eb7-11ea-8b60-9c6a7274e046.png)

It looks like the MCMC takes about 500 iterations to find the estimate, so we should remove those. Then we can get a mean point estimate and 95% credible interval:

burnin = 500
posterior_sample = mcmc.output$t.chain[,1][-c(1:burnin)]
mean(posterior_sample)
quantile(posterior_sample,probs=c(0.025, 0.975))

Let me know if you have any more trouble.

Joel

**Comment by Cecilia44** [comment]
Thank you so much for your detailed reply! 
I have another question for you. If I run 10 MCMC chains, and there are 10 mean values of TMRCA and confident intervals after removing the unconverged iterations, how can I choose the best one from the 10 values? 
Thanks again!

Cecilia

**Comment by jhavsmith** [comment]
In the past, we've taken the one with the highest mean posterior probability. Those values are in the second column of mcmc.output$t.chain. To compute that, you can do: 

mean(mcmc.output$t.chain[,2][-c(1:burnin)])

**Comment by Cecilia44** [comment]
Hi, Joel,
In your example of trace plot after running the example script from help(run.startmrca) with 5000 iterations, the TMRCA value decreases with increasing iterations. However, in my result, the TMRCA value increases with increasing iterations and eventually converges. Why is this so? Is this result available?

Cecilia

**Comment by xgdong** [comment]
Hi, Cecilia
In my result of running startmcra,  the TMRCA value also increases with increasing iterations , how did you deal with your results finally? and I also confused how to set the argument chain.length (the number of iterations for the MCMC to run).
Dong
