### ISSUE TITLE
How to decide the value for nsel and nanc?

### ISSUE THREAD

**Issue by wenbinmei** [jhavsmith/startmrca#2]
Hi Joel,

I am playing with startmrca to estimate the time of a hard sweep in maize.  So I have questions about how to decide the value for nsel and nanc? You have explanation in the manual but not so clearly for me, could you please explain in details? I have a vcf file including both selected individual and non-selective individuals? So nsel and nanc is the number of individuals for two types? Thank you.

nsel	: the sample size for the number of chromosomes with the selected allele to use.
nanc: the sample size for the reference panel of chromosomes without the selected allele.

Regards,
wenbin

**Comment by jhavsmith** [comment]
Hi Wenbin,

Thanks for your interest in using my method! Your VCF should have
individuals with the selected allele and individuals without the selected
allele. If that's not true, then you can't use the method. nsel is the
sample size you want to use for individuals in your VCF file that have the
selected allele. nanc is the number of individuals without the selected
allele that you want to use.

For my applications I've been able to use 100 for nsel and 20 for nanc. How
many individuals are in your VCF file, and how many of them have the
selected allele?

Cheers,
Joel

**Comment by wenbinmei** [comment]
Hi Joel,

Thanks for your reply.  I have about 1000 individuals with selected alleles and about 20 individuals without selected alleles. Also in my analysis, the vcf is combined maize and teosinte, all selected allele is fixed in maize and non-selected allele is fixed in teosinte. Is that ok for me to use your method? Also I don't have additional reference panel, I am using one vcf file to run the analysis, is that ok? Thank you.

Regards,
wenbin

**Comment by jhavsmith** [comment]
Yes, that's okay. I would recommend only using 100 individuals at a time
for nsel. There are two files that you will need to specify that include
the sample IDs for individuals with the selected allele (sample.ids) and
individuals without the selected allele (refsample.ids).

Joel

**Comment by jhavsmith** [comment]
You can also see the example I included at the bottom of the help file for
better illustration.

**Comment by wenbinmei** [comment]
Thank you, Joel.  I run your example files and produced two output files from MCMC, one is anchap.post and t.chain, could you explain more about the output files? Do I need to do anything else to get the estimated time of selection? Thanks.

Wenbin

**Comment by jhavsmith** [comment]
If you read the "Value" section at the bottom of the help file it explains
what is in each of those output files. The first column is the output from
the MCMC. Plot that over iterations. Look for how long it takes to converge
around some value, remove the first number of iterations that are not
converged. Then plot a histogram of those values. That's your estimate.

Joel

**Comment by wenbinmei** [comment]
Great, thank you for explaining all these things, Joel!

**Comment by Cecilia44** [comment]
> If you read the "Value" section at the bottom of the help file it explains what is in each of those output files. The first column is the output from the MCMC. Plot that over iterations. Look for how long it takes to converge around some value, remove the first number of iterations that are not converged. Then plot a histogram of those values. That's your estimate. Joel

Hi, Joel,
I also have some questions about the result of t.chain. I run 10 independent  MCMC chains with 10000 iterations. I have plotted the MCMC in the first column over iterations and found they are converged in each MCMC chains. Then how can I determine the exact TMRCA (mean value or median value of those converged values)? And how to calculate the confidence interval?

Thanks a lot!
