### ISSUE TITLE
Error when nanc = 1

### ISSUE THREAD

**Issue by saramathieson** [jhavsmith/startmrca#3]
Hi Joel - it has been great to try this out so far!  One small issue - if nanc = 1 there is a dimensionality error (interpreted as a vector not matrix?)  It is probably not ideal to have nanc so low anyway, but it happened in one of my datasets. Thanks!

**Comment by jhavsmith** [comment]
Yikes! Thanks for letting me know Sara. Any other comments you have would
be great.

Cheers!
Joel

**Comment by saramathieson** [comment]
Thanks Joel!
