### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by blogsdon** [jhavsmith/startmrca#4]
Tried to install with the commands from the markdown:

`library(devtools)`
`install_github("jhavsmith/startmrca@v0.6-1")`
`library(startmrca)`

Got this error:

Error: package or namespace load failed for ‘startmrca’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/startmrca/libs/startmrca.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/startmrca/libs/startmrca.so, 6): no suitable image found.  Did find:
	/Library/Frameworks/R.framework/Versions/3.4/Resources/library/startmrca/libs/startmrca.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Library/Frameworks/R.framework/Versions/3.4/Resources/library/startmrca/libs/startmrca.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

Session info:
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.2

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.4

loaded via a namespace (and not attached):
[1] httr_1.3.1     compiler_3.4.3 R6_2.2.2       tools_3.4.3    withr_2.1.1   
[6] curl_3.1       memoise_1.1.0  git2r_0.21.0   digest_0.6.14

**Comment by jhavsmith** [comment]
I was building the package locally then pushing it, so the .so and .o files
were getting in the way. I changed the setup to:

library(devtools)
install_github("jhavsmith/startmrca")
library(startmrca)

Check to see if that works.

Thanks,
Joel
