### ISSUE TITLE
System calls on VCF

### ISSUE THREAD

**Issue by fdchevalier** [jhavsmith/startmrca#6]
Hi Joel,

First, thank you for having made this useful package.

I was playing with it recently and wanted to test several parameters. To make it efficient, I wanted to run these tests in parallel but I quickly noticed that that was not possible because of the system calls made by the script to write temporary files. So I made some modifications to avoid this (by using [vcfR package](https://github.com/knausb/vcfR)). The other benefit of this is to make your package compatible with Windows system where system call using Unix commands may not work. In the meantime, I also improved output storage (in file and object).

If you are interested by these modifications, you can review them [here](https://github.com/fdchevalier/startmrca/commit/c59aeaa20007919ce3275118957233ee2d447645). Let me know if you want me to do a pull request.

For those interested to perform multiple startmrca runs at the same time, here is an example:

```R
library(doParallel)

mychain <- 1:10
registerDoParallel(cores=length(mychain))

foreach (chain = mychain) %doapar% {
     run.startmrca(vcf.file      = "examples/FIN_chr2_pos136608646.vcf.gz",
                   rec.file      = "examples/decode_recmap_sexaveraged.txt", 
                   sample.ids    = "examples/sample_ids.txt", 
                   refsample.ids = "examples/sample_ids.txt",
                   mut.rate      = 1.6e-8, 
                   nsel          = 50,
                   nanc          = 20,
                   chain.length  = 20,
                   nanc.post     = 10,
                   pos           = 136608646,
                   sel.allele    = 1
                   output.file   = paste0(,chain,"_mcmc_list.RDATA")))
}
```
**Note**: The only downside of the parallelization is the superimposed console messages  especially when using progress bar in parallel jobs. This could be solved by adding a verbose option to turn off progress info.

Fred

**Comment by jhavsmith** [comment]
Hi Fred,

Thanks for taking some interest in this! Yes, we can go ahead and make
these changes.

Joel
