### ISSUE TITLE
Error in if (!is.na(output.file)) 

### ISSUE THREAD

**Issue by magaliaguilera** [jhavsmith/startmrca#9]
Hi Joel

I have been trying to run your program but everytime I get the message: 
Error in if (!is.na(output.file)) { : argument is of length zero. It also says that is.na() is applied to a non list or vector of type NULL. Even when I specify output.file = NULL. Does this mean that the program isn't generating an output even though everything else runs normally? When I specify output.file = NA there is no error message. Thanks!

Magali

**Comment by Cecilia44** [comment]
Hi, Magali

I met the same problem as you, did you get any solution about it? 
Thanks!

**Comment by Cecilia44** [comment]
> Hi Joel
> 
> I have been trying to run your program but everytime I get the message:
> Error in if (!is.na(output.file)) { : argument is of length zero. It also says that is.na() is applied to a non list or vector of type NULL. Even when I specify output.file = NULL. Does this mean that the program isn't generating an output even though everything else runs normally? When I specify output.file = NA there is no error message. Thanks!
> 
> Magali

Hi, Magali

I met the same problem as you, did you get any solution about it?
Thanks!

**Comment by magaliaguilera** [comment]
Hi Cecilia,

Sorry for the delay. Have you already solved the problem? I can think of some ways that you can solve it. First of all, how are you calculating your nanc and nsel? Are you including an outgroup?

Cheers,
Magali

**Comment by jhavsmith** [comment]
Hi Cecilia and Magali,

Sorry for the delay--it should hopefully be resolved now. 

Joel
